Repository triton-inference-server/triton_distributed, pull requests merged in 2025-02, with the labels that each got.

#116 docs: readme + examples
  runtime/rust/README.md
  runtime/rust/docker-compose.yml
  runtime/rust/examples/hello_world/Cargo.lock
  runtime/rust/examples/hello_world/Cargo.toml
  runtime/rust/examples/hello_world/src/bin/client.rs
  runtime/rust/examples/hello_world/src/bin/server.rs
  runtime/rust/examples/hello_world/src/lib.rs
  runtime/rust/python-wheel/README.md
  runtime/rust/src/lib.rs
Labels: documentation

#113 feat: vLLM DistributedRuntime Monolith and Disagg Workers Example
  examples/python_rs/llm/vllm/README.md
  examples/python_rs/llm/vllm/common/__init__.py
  examples/python_rs/llm/vllm/common/client.py
  examples/python_rs/llm/vllm/common/parser.py
  examples/python_rs/llm/vllm/common/protocol.py
  examples/python_rs/llm/vllm/disaggregated/__init__.py
  examples/python_rs/llm/vllm/disaggregated/decode_worker.py
  examples/python_rs/llm/vllm/disaggregated/prefill_worker.py
  examples/python_rs/llm/vllm/monolith/__init__.py
  examples/python_rs/llm/vllm/monolith/worker.py
Labels: enhancement

#99 build: Support rebuilding and replacing trtllm backend
  container/Dockerfile
  container/build.sh
  container/deps/clone_tensorrtllm.sh
Labels: enhancement

#167 feat: vLLM v0.7.2 patch supporting XpYd and heterogeneous P/D parallel configs
  .dockerignore
  .pre-commit-config.yaml
  container/Dockerfile
  container/build.sh
  container/deps/requirements.vllm.txt
  container/deps/vllm/README.md
  container/deps/vllm/data_plane/data_plane.py
  container/deps/vllm/data_plane/kv_cache.py
  container/deps/vllm/install.sh
  container/deps/vllm/prepare_patch.sh
  container/deps/vllm/prepare_wheel.sh
  container/deps/vllm/tests/test_patch_install.py
  container/deps/vllm/vllm_patch_063post1.patch
  container/deps/vllm/vllm_v0.7.2.patch
  examples/python/llm/vllm/README.md
  examples/python_rs/llm/vllm/README.md
  examples/python_rs/llm/vllm/common/client.py
  examples/python_rs/llm/vllm/disaggregated/decode_worker.py
  examples/python_rs/llm/vllm/disaggregated/prefill_worker.py
Labels: enhancement

#174 feat: Add `tio` your friendly cmd line uncle to run triton-llm services
  .github/workflows/pre-merge-rust.yml
  applications/llm/bin/tio/Cargo.lock
  applications/llm/bin/tio/Cargo.toml
  applications/llm/bin/tio/rust-toolchain.toml
  applications/llm/bin/tio/src/input.rs
  applications/llm/bin/tio/src/input/http.rs
  applications/llm/bin/tio/src/input/text.rs
  applications/llm/bin/tio/src/lib.rs
  applications/llm/bin/tio/src/main.rs
  applications/llm/bin/tio/src/opt.rs
  applications/llm/bin/tio/src/output.rs
  applications/llm/bin/tio/src/output/echo_full.rs
Labels: enhancement

#186 fix: Unique IDs for mistralrs requests
  applications/llm/bin/tio/Cargo.lock
  llm/rust/Cargo.lock
  llm/rust/triton-llm/Cargo.toml
  llm/rust/triton-llm/src/engines/mistralrs.rs
Labels: bug

#203 bug: tio can run without NATS or ETCD
  applications/llm/bin/tio/src/main.rs
Labels: bug

#223 feat(tio): Defaults for in and out, support HF repos
  .gitignore
  applications/llm/bin/tio/README.md
  applications/llm/bin/tio/src/lib.rs
  applications/llm/bin/tio/src/main.rs
  llm/rust/triton-llm/src/engines/mistralrs.rs
  llm/rust/triton-llm/src/kv_router.rs
  llm/rust/triton-llm/src/kv_router/scheduler.rs
Labels: enhancement

#224 ci: Add Biswa and Thomas as Rust reviewers
  CODEOWNERS
Labels: documentation

#226 Create docs wokflow
  .github/workflows/docs_update_ci.yml
  CODEOWNERS
Labels: documentation

#235 feat(tio): Distributed inference!
  applications/llm/tio/README.md
  applications/llm/tio/src/input.rs
  applications/llm/tio/src/input/endpoint.rs
  applications/llm/tio/src/input/http.rs
  applications/llm/tio/src/input/text.rs
  applications/llm/tio/src/lib.rs
  applications/llm/tio/src/main.rs
  applications/llm/tio/src/opt.rs
  llm/rust/triton-llm/Cargo.toml
  llm/rust/triton-llm/src/http/service/discovery.rs
  llm/rust/triton-llm/src/lib.rs
  llm/rust/triton-llm/src/model_card.rs
  llm/rust/triton-llm/src/model_card/create.rs
  llm/rust/triton-llm/src/model_card/model.rs
  llm/rust/triton-llm/tests/model_card.rs
  runtime/rust/src/component.rs
  runtime/rust/src/component/client.rs
  runtime/rust/src/logging.rs
Labels: enhancement

#237 chore: add instructions to build env
  examples/python_rs/llm/tensorrt_llm/README.md
Labels: documentation

#250 feat(cai): working container build for multiple nova-services
  Dockerfile.cai
  compoundai/pyproject.toml
  compoundai/src/compoundai/__init__.py
  compoundai/src/compoundai/sdk/image.py
  compoundai/uv.lock
  examples/python_rs/llm/vllm/disaggregated/README-NOVA-INIT.md
  examples/python_rs/llm/vllm/disaggregated/client.py
Labels: documentation

#265 feat: tio support preprocessor
  applications/llm/tio/src/input/endpoint.rs
  applications/llm/tio/src/input/http.rs
  applications/llm/tio/src/input/text.rs
  applications/llm/tio/src/lib.rs
  applications/llm/tio/src/opt.rs
  applications/llm/tio/src/output.rs
  applications/llm/tio/src/output/echo_core.rs
  lib/llm/src/model_card/create.rs
  lib/llm/tests/preprocessor.rs
Labels: enhancement

#263 refactor: adds `TryFrom<&str>` and `FromStr` for `Endpoint`
  .gitignore
  applications/llm/tio/src/input/endpoint.rs
  applications/llm/tio/src/lib.rs
  lib/runtime/src/pipeline/error.rs
  lib/runtime/src/protocols.rs
Labels: documentation, enhancement

#271 feat: sglang backend for tio
  applications/llm/count/Cargo.lock
  examples/rust/Cargo.lock
  launch/tio/Cargo.lock
  launch/tio/Cargo.toml
  launch/tio/README.md
  launch/tio/src/lib.rs
  launch/tio/src/main.rs
  launch/tio/src/net.rs
  launch/tio/src/opt.rs
  lib/bindings/c/Cargo.lock
  lib/bindings/python/Cargo.lock
  lib/llm/Cargo.lock
  lib/llm/Cargo.toml
  lib/llm/src/engines.rs
  lib/llm/src/engines/sglang.rs
  lib/llm/src/engines/sglang/engine.rs
  lib/llm/src/engines/sglang/subprocess.rs
  lib/llm/src/engines/sglang/worker.rs
Labels: enhancement

#277 feat: Endpoint defaults for namespace/component/other
  lib/runtime/src/protocols.rs
Labels: enhancement

#261 refactor: using async_openai
  applications/llm/count/Cargo.lock
  examples/rust/Cargo.lock
  launch/tio/Cargo.lock
  launch/tio/Cargo.toml
  launch/tio/src/input/text.rs
  launch/tio/src/output/echo_full.rs
  lib/bindings/c/Cargo.lock
  lib/bindings/python/Cargo.lock
  lib/llm/Cargo.lock
  lib/llm/Cargo.toml
  lib/llm/src/engines/mistralrs.rs
  lib/llm/src/http/service/openai.rs
  lib/llm/src/preprocessor.rs
  lib/llm/src/preprocessor/prompt/template/oai.rs
  lib/llm/src/protocols/common.rs
  lib/llm/src/protocols/openai.rs
  lib/llm/src/protocols/openai/chat_completions.rs
  lib/llm/src/protocols/openai/chat_completions/aggregator.rs
  lib/llm/src/protocols/openai/chat_completions/delta.rs
  lib/llm/src/protocols/openai/completions.rs
  lib/llm/src/protocols/openai/completions/aggregator.rs
  lib/llm/src/types.rs
  lib/llm/tests/aggregators.rs
  lib/llm/tests/http-service.rs
  lib/llm/tests/openai_completions.rs
  lib/llm/tests/preprocessor.rs
Labels: enhancement

#182 feat: LLM API example integration
  container/Dockerfile
  container/build.sh
  examples/python_rs/llm/tensorrt_llm/README.md
  examples/python_rs/llm/tensorrt_llm/common/__init__.py
  examples/python_rs/llm/tensorrt_llm/common/client.py
  examples/python_rs/llm/tensorrt_llm/common/parser.py
  examples/python_rs/llm/tensorrt_llm/common/protocol.py
  examples/python_rs/llm/tensorrt_llm/disaggregated/__init__.py
  examples/python_rs/llm/tensorrt_llm/disaggregated/llmapi_disaggregated_configs/multi_node_config.yaml
  examples/python_rs/llm/tensorrt_llm/disaggregated/llmapi_disaggregated_configs/single_node_config.yaml
  examples/python_rs/llm/tensorrt_llm/disaggregated/router.py
  examples/python_rs/llm/tensorrt_llm/disaggregated/worker.py
  examples/python_rs/llm/tensorrt_llm/model.json
  examples/python_rs/llm/tensorrt_llm/monolith/__init__.py
  examples/python_rs/llm/tensorrt_llm/monolith/worker.py
  pyproject.toml
Labels: enhancement

#284 refactor: rename ChatCompletionRequest to NvCreateChatCompletionRequest
  launch/tio/src/input/endpoint.rs
  launch/tio/src/input/http.rs
  launch/tio/src/input/text.rs
  launch/tio/src/lib.rs
  launch/tio/src/output/echo_full.rs
  lib/llm/src/http/service/discovery.rs
  lib/llm/src/http/service/openai.rs
  lib/llm/src/preprocessor.rs
  lib/llm/src/preprocessor/prompt/template/oai.rs
  lib/llm/src/protocols/openai/chat_completions.rs
  lib/llm/src/protocols/openai/chat_completions/delta.rs
  lib/llm/src/types.rs
  lib/llm/tests/http-service.rs
  lib/llm/tests/preprocessor.rs
Labels: enhancement

#292 refactor: rename ChatCompletionResponseDelta to NvCreateChatCompletionStreamResponse
  launch/tio/src/input/endpoint.rs
  launch/tio/src/input/http.rs
  launch/tio/src/input/text.rs
  launch/tio/src/lib.rs
  launch/tio/src/output/echo_full.rs
  lib/llm/src/engines/mistralrs.rs
  lib/llm/src/http/service/discovery.rs
  lib/llm/src/preprocessor.rs
  lib/llm/src/protocols/codec.rs
  lib/llm/src/protocols/openai/chat_completions.rs
  lib/llm/src/protocols/openai/chat_completions/aggregator.rs
  lib/llm/src/protocols/openai/chat_completions/delta.rs
  lib/llm/src/types.rs
  lib/llm/tests/http-service.rs
Labels: enhancement

#296 refactor: removes wrapper for ChatCompletionContent and adds documentation
  lib/llm/src/protocols/openai/chat_completions.rs
  lib/llm/src/protocols/openai/chat_completions/aggregator.rs
  lib/llm/src/protocols/openai/chat_completions/delta.rs
Labels: documentation, enhancement

#297 fix: add skip_serializing if none
  lib/llm/src/protocols/openai/chat_completions.rs
Labels: bug

#298 feat: llama.cpp engine for tio
  launch/tio/Cargo.lock
  launch/tio/Cargo.toml
  launch/tio/README.md
  launch/tio/src/lib.rs
  launch/tio/src/main.rs
  launch/tio/src/opt.rs
  lib/llm/Cargo.lock
  lib/llm/Cargo.toml
  lib/llm/src/engines.rs
  lib/llm/src/engines/llamacpp.rs
  lib/llm/src/engines/mistralrs.rs
Labels: enhancement

#308 feat: vllm engine
  launch/tio/Cargo.toml
  launch/tio/README.md
  launch/tio/src/lib.rs
  launch/tio/src/main.rs
  launch/tio/src/opt.rs
  lib/llm/Cargo.toml
  lib/llm/src/engines.rs
  lib/llm/src/engines/vllm.rs
  lib/llm/src/engines/vllm/engine.rs
  lib/llm/src/engines/vllm/subprocess.rs
  lib/llm/src/engines/vllm/worker.rs
Labels: enhancement

#310 refactor: use async-openai CompletionRequest
  lib/llm/src/http/service/openai.rs
  lib/llm/src/preprocessor/prompt/template/oai.rs
  lib/llm/src/protocols/openai.rs
  lib/llm/src/protocols/openai/completions.rs
  lib/llm/src/protocols/openai/completions/delta.rs
  lib/llm/tests/http-service.rs
  lib/llm/tests/openai_completions.rs
  lib/llm/tests/snapshots/openai_completions__valid_samples-2.snap
  lib/llm/tests/snapshots/openai_completions__valid_samples-5.snap
  lib/llm/tests/snapshots/openai_completions__valid_samples-6.snap
  lib/llm/tests/snapshots/openai_completions__valid_samples-8.snap
Labels: enhancement
